# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
# =======================  Configuration of EdgeLock 2GO Offline Provisioning flow for mcxn947  ========================

# ======================================================================================================================
#                                                 == General Options ==
# ======================================================================================================================
# ------------------------------------------===== MCU family [Required] =====-------------------------------------------
# Description: Family identifier including the chip revision. If revision is not present, latest revision is used as
# default.
family: mcxn947
# -----------------------------------------===== MCU revision [Optional] =====------------------------------------------
# Description: Revision of silicon
revision: latest
# -------------------------------------===== EdgeLock 2GO API URL [Optional] =====--------------------------------------
# Description: Base URL of the EdgeLock 2GO backend API without an / at the end
url: https://api.qa.sb.edgelock2go.com
# -------------------------------------===== EdgeLock 2GO API Key [Required] =====--------------------------------------
# Description: REST API key used for user authentication in EdgeLock 2GO. You may use: 1) path to a file with the key on
# the first line: ~/.el2go/wpc_token.txt (~ is interpreted as your HOME) 2) environment variable with the key:
# $MY_EL2GO_KEY 3) environment variable containing a path to the key file: $MY_KEY_FILE 4) directly your API key in
# plain text (not recommended)
api_key: ~/.el2go/qa_token.txt
# ----------------------------------------===== Device Group ID [Required] =====----------------------------------------
# Description: Device Group ID in which the connected secure element needs to be assigned
device_group_id: 648
# -----------------------------------------===== Product 12NC [Required] =====------------------------------------------
# Description: Product 12NC registered in EdgeLock 2GO
nc12: 340000274521
# ------------------------------------===== Secure Objects Domains [Optional] =====-------------------------------------
# Description: List of the EdgeLock 2GO Secure Objects Domains to download.
# Possible options: <RTP, MATTER>
domains:
  - RTP
  - MATTER
# ----------------------------===== Delay between EdgeLock 2GO's API calls [Optional] =====-----------------------------
# Description: Delay in seconds between EdgeLock 2GO API requests regarding Secure Objects generation status. Default
# value is 5 seconds
delay: 5
# ---------------------------------===== Timeout for EdgeLock 2GO API [Optional] =====----------------------------------
# Description: Timeout in seconds of downloading Secure Objects through EdgeLock 2GO API operation. Default is 60
# seconds
timeout: 60
# ---------------------------------------===== Download Timeout [Optional] =====----------------------------------------
# Description: Timeout for overall download process including waiting for Secure Objects creation
download_timeout: 300
# -------------------------------------===== Provisioning FW path [Required] =====--------------------------------------
# Description: Path to OEM Provisioning Firmware SB file
prov_fw_path: N10_A1_EL2GO_OEM_PROV_RC2.sb3
# ----------------------===== Address for External (user-defined) Secure Objects [Required] =====-----------------------
# Description: Address where to store External (user-defined) Secure Objects obtained from EL2GO. External Secure
# Objects refers to Secure Objects other than OEM FW Authentication Key Hash, and OEM FW Decryption Key. Please note
# that the FW will always erase 8K memory block (flash page size) in the destination address, so any data previously
# stored at that flash location will be gone. If you don't use any External Secure Objects, this setting has no effect
secure_objects_address: 0x1000
