# Copyright 2023-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# Path to CMPA binary
cmpa_path: sample_config_data/cmpa_example.bin
# Path to CFPA binary
cfpa_path: sample_config_data/cfpa_example.bin
# Path to SB file Key Encryption Key
sb_kek_path: sample_config_data/sb_kek_example.txt
# Path to USER Key Encryption Key
user_kek_path: sample_config_data/user_kek_example.txt

# Production quota
production_quota: 1_000_000

# Number of OEM certificates to generate
# If it's set to 0, rest of this section is ignored
oem_id_count: 0

# Path to key for Audit log signing
oem_log_prk_path: sample_config_data/oem_log_prk.pem

# Path to nxp_glob attestation certificate
nxp_global_attest_puk_path: sample_config_data/nxp_glob_devattest_cert.crt

# Path to device family attestation certificate
nxp_prod_cert_path: sample_config_data/nxp_prod_devattest_cert.crt

# Signing key path (PEM or DER encoded P-256 ECC Key)
oem_id_prk_path: sample_config_data/oem_id_prk.pem
