# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: project-words
    path: "./project-words.txt"
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - "venv**"
  - "__pycache__**"
  - "_build**"
  - "/project-words.txt"
  - "approved_packages.json"
  - "reports/**"
  - "build/**"
  - "dist/**"
  - "*egg-info/**"
  - "tests/utils/data/file_special.txt"
  - "spsdk/__version__.py"
