# Copyright 2021-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

data:
  cfpa_path: y_cfpa.bin
  cmpa_path: y_cmpa.bin
  family: lpc55s6x
  nxp_global_attest_puk_path: y_nxp_glob_attest_puk.pub
  nxp_prod_cert_path: y_nxp_prod_cert.der.crt
  nxp_prod_card_prk_path: nxp_prod_card_auth_prk.pem
  oem_cert_0_addr:
  oem_cert_0_path: x_oem_cert_0.crt
  oem_cert_1_addr:
  oem_cert_1_path: x_oem_cert_1.crt
  oem_cert_2_addr:
  oem_cert_2_path: x_oem_cert_2.crt
  oem_cert_3_addr:
  oem_cert_3_path: x_oem_cert_3.crt
  oem_cert_4_addr:
  oem_cert_4_path: x_oem_cert_4.crt
  oem_cert_ca_addr:
  oem_cert_ca_path: x_oem_cert_ca.crt
  oem_cert_rtf_addr:
  oem_cert_rtf_path: x_oem_cert_rtf.crt
  oem_id_config:
  oem_id_count:
  oem_id_meta:
  oem_id_prk_path: y_oem_id_prk.pem
  oem_id_template: y_oem_id_template.der.crt
  oem_log_prk_path: y_oem_log_prk.pem
  production_quota:
  prov_data_path: y_prov_data.sb3
  sb_kek_path: y_sb_kek.txt
  user_kek_path: y_user_kek.txt
description: TP Device Model
do_encryption: true
do_wrapping: false
edh_private_path: x_edh_private.pem
edh_public_path: x_edh_public.pem
id: "123456789"
is_ready: true
name: card1
prov_enc_const: 0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00
prov_kwk_const: 0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00
prov_mac_const: 0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00
reuse_edh_keys: false
reuse_oem_cert: false
reuse_ses_keys: false
tp_ses_enc_path: x_tp_ses_enc.txt
tp_ses_kwk_path: x_tp_ses_kwk.txt
tp_ses_mac_path: x_tp_ses_mac.txt
use_prov_data: true
