# Copyright 2023-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
data:
  cfpa_path: x_cfpa.bin
  cmpa_path: x_cmpa.bin
  oem_id_0_private: x_oem_id_0_private.pem
  oem_id_0_public: x_oem_id_0_public.pem
  oem_id_0_cert: x_oem_id_0_cert.crt
  oem_id_1_private: x_oem_id_1_private.pem
  oem_id_1_public: x_oem_id_1_public.pem
  oem_id_1_cert: x_oem_id_1_cert.crt
  oem_id_2_private: x_oem_id_2_private.pem
  oem_id_2_public: x_oem_id_2_public.pem
  oem_id_2_cert: x_oem_id_2_cert.crt
  oem_id_3_private: x_oem_id_3_private.pem
  oem_id_3_public: x_oem_id_3_public.pem
  oem_id_3_cert: x_oem_id_3_cert.crt
  oem_id_4_private: x_oem_id_4_private.pem
  oem_id_4_public: x_oem_id_4_public.pem
  oem_id_4_cert: x_oem_id_4_cert.crt
  oem_id_ca_private: x_oem_id_ca_private.pem
  oem_id_ca_public: x_oem_id_ca_public.pem
  oem_id_ca_cert: x_oem_id_ca_cert.crt
  oem_id_rtf_private: x_oem_id_rtf_private.pem
  oem_id_rtf_public: x_oem_id_rtf_public.pem
  oem_id_rtf_cert: x_oem_id_rtf_cert.crt
  prov_data_path: x_prov_data.sb3
  sb_kek_path: x_sb_kek.txt
  user_kek_path: x_user_kek.txt
ecid: EC0102030405060708090a0b0c0d0e0f
uuid: DD0102030405060708090a0b0c0d0e0f
description: TP Target Model
do_encryption: true
do_wrapping: false
edh_private_path: x_edh_private.pem
edh_public_path: x_edh_public.pem
id: "com3"
is_ready: true
name: lpc55s16
family: lpc55s1x
nxp_die_id_cert_path: x_nxp_die_devattest_id_cert.bin
nxp_die_id_prk_path: x_nxp_die_devattest_id_prk.pem
nxp_die_id_puk_path: x_nxp_die_devattest_id_puk.pem
nxp_die_id_attest_prk_path: x_nxp_die_id_attest_id_prk.pem
nxp_die_id_attest_puk_path: x_nxp_die_id_attest_id_puk.pem
nxp_prod_card_auth_puk_path: nxp_prod_card_auth_puk.pem
nxp_prod_devattest_prk_path: nxp_prod_devattest_prk.pem
reuse_die_id_keys: true
prov_enc_const: 0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00
prov_kwk_const: 0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00
prov_mac_const: 0102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f00
reuse_edh_keys: false
reuse_oem_cert: false
reuse_ses_keys: false
tp_ses_enc_path: x_tp_ses_enc.txt
tp_ses_kwk_path: x_tp_ses_kwk.txt
tp_ses_mac_path: x_tp_ses_mac.txt
use_prov_data: true
